Rinkudesu.Gateways.Webui/Rinkudesu.Gateways.Webui/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Rinkudesu.Gateways.Clients.Links;
using Rinkudesu.Gateways.Clients.LinkTags;
using Rinkudesu.Gateways.Utils;
using Rinkudesu.Gateways.Webui.Models;
using Rinkudesu.Gateways.Webui.Utils;

namespace Rinkudesu.Gateways.Webui.Controllers
{
    [Authorize]
    public class LinksController : AccessTokenClientController<LinksClient>
    {
        private readonly IStringLocalizer<LinksController> _localizer;
        private readonly IMapper _mapper;

        public LinksController(IMapper mapper, LinksClient client, IStringLocalizer<LinksController> localizer) : base(client)
        {
            _mapper = mapper;
            _localizer = localizer;
        }

        [HttpGet]
        public IActionResult Index([FromQuery] LinkIndexQueryModel query)
        {
            return View(query);
        }

        [HttpGet]
        public async Task<ActionResult> IndexContent([FromQuery] LinkIndexQueryModel query, [FromServices] LinkTagsClient linkTagsClient, Uri returnUrl, CancellationToken cancellationToken)
        {
            if (!ModelState.IsValid) return BadRequest("Provided query is not valid.");

            await linkTagsClient.SetAccessToken(HttpContext.Request);
            await SetJwt();
            var links = await Client.GetLinks(_mapper.Map<LinkQueryDto>(query), cancellationToken);
            if (links is null)
                return NotFound();
            var linkModels = _mapper.Map<List<LinkIndexViewModel>>(links.ToList());

            foreach (var link in linkModels)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var tags = await linkTagsClient.GetTagsForLink(link.Id, cancellationToken);
                if (tags is null) return BadRequest("We were unable to process tags assigned to links.");
                link.LinkTags.AddRange(tags);
            }

            ViewData["ReturnUrl"] = returnUrl;
            ViewData["Query"] = query;
            return PartialView(linkModels);
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] LinkIndexViewModel newLink, [FromServices] LinkTagsClient linkTagsClient)
        {
            if (!ModelState.IsValid)
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri());

            var newLinkDto = _mapper.Map<LinkDto>(newLink);

            await SetJwt();
            var returnedDto = await Client.CreateLink(newLinkDto);
            if (returnedDto is null)
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri(), _localizer["unableToCreate"]);
            await linkTagsClient.SetAccessToken(HttpContext.Request);
            foreach (var tagId in newLink.TagIds)
            {
                //todo: consider some sort of error handling here, as the link already exists at this point, but just quietly failing to create tags is not the best option
                await linkTagsClient.Assign(new() { LinkId = returnedDto.Id, TagId = tagId });
            }
            return Redirect(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> QuickCreate(Uri? url, Uri returnUrl)
        {
            if (url is null)
                return this.ReturnBadRequest(returnUrl, _localizer["missingUrl"]);

            var newLink = new LinkDto { Title = LinkDto.LimitQuickAddTitle(url), LinkUrl = url, PrivacyOptions = LinkPrivacyOptionsDto.Private };

            await SetJwt();
            var isSuccess = await Client.CreateLink(newLink) is not null;
            if (!isSuccess)
            {
                if (Client.LastErrorReturned == "Link already exists")
                    return this.ReturnBadRequest(returnUrl, _localizer["alreadyExists"]);
                return this.ReturnBadRequest(returnUrl, _localizer["unableToCreate"]);
            }
            return LocalRedirect(returnUrl.ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string? id, Uri returnUrl)
        {
            if (string.IsNullOrEmpty(id))
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri(), _localizer["missingId"]);
            if (!Guid.TryParse(id, out var guid))
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri(), _localizer["invalidId"]);

            await SetJwt();
            if (!await Client.Delete(guid))
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri(), _localizer["unableToDelete"]);

            return LocalRedirect(returnUrl.ToString());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id, Uri returnUrl, CancellationToken token)
        {
            if (string.IsNullOrEmpty(id) || !Guid.TryParse(id, out var guid))
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri(), _localizer["invalidId"]);

            await SetJwt();
            var link = await Client.GetLink(guid, token);

            if (link is null)
                return this.ReturnNotFound(Url.ActionLink(nameof(Index))!.ToUri());
            ViewData["ReturnUrl"] = returnUrl;
            return View(_mapper.Map<LinkIndexViewModel>(link));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string? id, [Bind] LinkDto editLink, Uri returnUrl)
        {
            if (!Guid.TryParse(id, out var guid) || !ModelState.IsValid)
                return this.ReturnBadRequest(Url.ActionLink(nameof(Index))!.ToUri(), _localizer["invalidId"]);

            await SetJwt();
            var result = await Client.Edit(guid, editLink);

            if (!result)
                return this.ReturnNotFound(Url.ActionLink(nameof(Index))!.ToUri());
            return LocalRedirect(returnUrl.ToString());
        }
    }
}

Rinkudesu.Gateways.Webui/Rinkudesu.Gateways.Webui/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Rinkudesu.Gateways.Clients.Tags;
using Rinkudesu.Gateways.Utils;
using Rinkudesu.Gateways.Webui.Models;
using Rinkudesu.Gateways.Webui.Utils;

namespace Rinkudesu.Gateways.Webui.Controllers;

[Authorize]
public class TagsController : AccessTokenClientController<TagsClient>
{
    private readonly IMapper _mapper;
    private readonly IStringLocalizer<TagsController> _localizer;

    public TagsController(TagsClient client, IMapper mapper, IStringLocalizer<TagsController> localizer) : base(client)
    {
        _mapper = mapper;
        _localizer = localizer;
    }

    [HttpGet]
    public IActionResult Index([Bind] TagIndexQueryModel query)
    {
        return View(query);
    }

    [HttpGet]
    public async Task<ActionResult> IndexContent([Bind] TagIndexQueryModel query, Uri returnUrl, CancellationToken cancellationToken)
    {
        await SetJwt();
        var tags = await Client.GetTags(_mapper.Map<TagQueryDto>(query), cancellationToken);
        if (tags is null)
            return NotFound();

        ViewData["ReturnUrl"] = returnUrl;
        ViewData["Query"] = query;
        return PartialView(_mapper.Map<List<TagIndexViewModel>>(tags));
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind] TagDto newTag)
    {
        var redirectUri = Url.ActionLink(nameof(Index))!.ToUri();
        if (!ModelState.IsValid)
            return this.ReturnBadRequest(redirectUri);

        await SetJwt();
        var isSuccess = await Client.CreateTag(newTag) is not null;
        if (!isSuccess)
        {
            if (Client.LastErrorReturned == "Tag already exists")
                return this.ReturnBadRequest(redirectUri, _localizer["tagExists"]);

            return this.ReturnBadRequest(redirectUri);
        }
        return Redirect(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id, Uri returnUrl, CancellationToken cancellationToken)
    {
        if (id == Guid.Empty)
            return this.ReturnBadRequest(returnUrl);

        await SetJwt();
        var tag = await Client.GetTag(id, cancellationToken);

        if (tag is null)
            return this.ReturnNotFound(returnUrl);
        ViewData["ReturnUrl"] = returnUrl;
        return View(tag);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, [Bind] TagDto editTag, Uri returnUrl, CancellationToken cancellationToken)
    {
        if (id == Guid.Empty || !ModelState.IsValid)
            return this.ReturnBadRequest(returnUrl);

        await SetJwt();
        var result = await Client.Edit(id, editTag, cancellationToken);

        if (!result)
        {
            if (Client.LastErrorReturned == "Tag already exists")
                return this.ReturnBadRequest(returnUrl, _localizer["tagExists"]);

            return this.ReturnNotFound(returnUrl);
        }
        return LocalRedirect(returnUrl.ToString());
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(Guid id, Uri returnUrl, CancellationToken cancellationToken)
    {
        if (id == Guid.Empty)
            return this.ReturnBadRequest(returnUrl);

        await SetJwt();
        var result = await Client.Delete(id, cancellationToken);

        if (!result)
            return this.ReturnBadRequest(returnUrl);
        return LocalRedirect(returnUrl.ToString());
    }
}

Rinkudesu.Gateways.Webui/Rinkudesu.Gateways.Webui/Views/Shared/_Layout.cshtml
@using Rinkudesu.Gateways.Webui.Utils
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    @*CSP definition*@
    <meta
        http-equiv="Content-Security-Policy"
        content="default-src 'self';
               script-src 'self'
                          https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
                          https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js
                          https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js
                          https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js
                          https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js;
               style-src  'self'
                          https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css
                          https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css
                          https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.bootstrap5.min.css
                          https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css;
               img-src    'self' data:;
               font-src   https://cdnjs.cloudflare.com/" />
    <title>@ViewData["Title"] - Rinkudesu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css" integrity="sha256-kki8QK1FtGejLIMu2MKBziAILQ7iEkEOSfE22i4KEU8=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.bootstrap5.min.css" integrity="sha256-SniYkctMAi1AF7xCGANZDFKlFTlfwb1rdWc0RLwkBNM=" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">(Insert favicon here)</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Links" asp-action="Index">@Localizer["links"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Tags" asp-action="Index">@Localizer["tags"]</a>
                    </li>
                    @if (User.IsAdmin())
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @Localizer["admin"]
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AccountAdmin">@Localizer["accountAdmin"]</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year.ToString() - Rinkudesu
    </div>
</footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js" integrity="sha256-bl5dZlrBcWpmPlZGgBBy9VGPGacsZVi7vHCAfZ2by6A=" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Rinkudesu.Gateways.Webui/Rinkudesu.Gateways.Webui/Views/Shared/_LinkDetails.cshtml
@model Rinkudesu.Gateways.Clients.Links.LinkDto

@{
    var colTitle = "col-2";
    var colValue = "col-10";
}

<div class="row">
    <div class="@colTitle">
        @Html.DisplayNameFor(m => m.Title)
    </div>
    <div class="@colValue">
        @Html.DisplayFor(m => m.Title)
    </div>
</div>
<div class="row">
    <div class="@colTitle">
        @Html.DisplayNameFor(m => m.Description)
    </div>
    <div class="@colValue">
        @Html.DisplayFor(m => m.Description)
    </div>
</div>
<div class="row">
    <div class="@colTitle">
        @Html.DisplayNameFor(m => m.LinkUrl)
    </div>
    <div class="@colValue">
        <a href="@Model!.LinkUrl">@Html.DisplayFor(m => m.LinkUrl)</a>
    </div>
</div>